### ISSUE TITLE
adapty and adapty ui  version conflicts

### ISSUE THREAD

**Issue by kartikApplore** [adaptyteam/AdaptyUI-Flutter#10]
[!] CocoaPods could not find compatible versions for pod "Adapty":
  In Podfile:
    adapty_flutter (from `.symlinks/plugins/adapty_flutter/ios`) was resolved to 2.9.0, which depends on
      Adapty (= 2.9.1)

    adapty_ui_flutter (from `.symlinks/plugins/adapty_ui_flutter/ios`) was resolved to 2.0.2, which depends on
      AdaptyUI (= 2.0.2) was resolved to 2.0.2, which depends on
        Adapty (~> 2.7.0)

**Comment by x401om** [comment]
Hi @kartikApplore, it is not possible to use AdaptyUI with the 2.9.x, we are going to update it soon.

**Comment by wal33d006** [comment]
@x401om 
Do we have any update on when do we get an update?
Also, if both of these packages are interdependent, one should not have been updated. This is causing major breaking in the running apps. I can't even put up simple startup integration for paywall integrations.

**Comment by x401om** [comment]
@wal33d006 I apologize for any inconvenience caused. We anticipate the release of the new version later this week or early next week. Currently, it is possible to use Paywall Builder with Adapty 2.7.x and AdaptyUI 2.0.x.

**Comment by Demirzekk** [comment]
Problem is going. How can ı resolve it?
