### ISSUE TITLE
MissingPluginException When Displaying Adapty UI After App Launch via FCM Push Notification

### ISSUE THREAD

**Issue by MarklBcm** [adaptyteam/AdaptyUI-Flutter#12]
I am encountering an issue where the Adapty UI fails to display with the following error when the app is launched via an FCM push notification:
`MissingPluginException(No implementation found for method create_view on channel flutter.adapty.com/adapty_ui)`

This issue occurs under the following conditions:
	1.	The app is terminated.
	2.	The app is launched via an FCM push notification.
	3.	The user attempts to display the Adapty UI.

Environment:
	•	Adapty SDK Version: 2.10.1
	•	Adapty UI Version: 2.1.2
	•	Flutter Version: 3.22.2
	•	Platform: [Android]
	•	OS Version: [Android 9, Android 10, Android 13(sometimes)]

Additional Context:
This error does not occur on all devices, but seems to be specific to certain device models or OS versions. The issue might be related to the timing of Flutter plugin initialization when the app is launched via a notification.

Would appreciate any guidance or a potential fix for this issue. Thank you!

**Comment by x401om** [comment]
Hey @MarklBcm! It seems like you have to initialize plugin by yourself before accessing its methods. I hope this related issues will help you:

1) https://github.com/firebase/flutterfire/issues/8204
2) https://github.com/flutter/flutter/issues/99155

**Comment by MarklBcm** [comment]
Thanks to your help, I’ve learned something new. However, I still haven’t found a way to resolve the issue.

In my case, the issue also occurs in the release build.

I’d like to report an additional related issue:

When the app is closed using the physical back button on Android and then reopened, the same MissingPluginException occurs.
 • I temporarily resolved this issue by using Exit(), but I don’t think this is the best solution.

**Comment by maru-eom** [comment]
I’m experiencing an issue where the CrossplatformUiHelper.init(flutterPluginBinding.applicationContext) method fails, resulting in the MethodChannel not being initialized. This leads to the AdaptyUiFlutterPlugin throwing an exception

**Comment by maru-eom** [comment]
I modified the code as follows:

`override fun onAttachedToEngine(flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
    val initialized = CrossplatformUiHelper.init(flutterPluginBinding.applicationContext)
    if (!initialized) {
        Log.d("AdaptyUiFlutterPlugin", "CrossplatformUiHelper.init failed.")
    }

    channel = MethodChannel(flutterPluginBinding.binaryMessenger, CHANNEL_NAME).also { channel ->
        channel.setMethodCallHandler(this)
    }
    channel?.let { channel -> callHandler.handleUiEvents(channel) }
}`

It works well.

Could this change potentially cause any other issues?

**Comment by x401om** [comment]
@maru-eom In my experience, as long as you have properly initialized the plugin and the channels, there should not be any issues.

It seems like we have the answer to the initial question, so I am going to close the issue.

**Comment by sajithlascade** [comment]
why are you closing this issue?? this is major issue. please merge the code mentioned by @maru-eom . and release new version asap.

**Comment by rignaneseleo** [comment]
I've found the same error `MissingPluginException(No implementation found for method create_view on channel flutter.adapty.com/adapty_ui)` in my users logs. It seems it happens right after the app goes to background and then resumed.

This happened on a Pixel 8 PRO with android 14:
![image](https://github.com/user-attachments/assets/adb1e969-64f7-4402-a325-5884149a045b)

This is my code:
 ```
try {
      Log.info("Presenting paywall...");

      Log.info("Creating paywall view...");
      final view = await _adaptyUI.createPaywallView(
        paywall: await paywall,
        locale: _kPaywallLocale,
      );
      Log.info("Paywall view created successfully");

      await view.present();
      Log.info("Paywall presented successfully");
      return true;
    } on AdaptyError catch (adaptyError) {
      Log.error("Adapty error while showing paywall: ${adaptyError.message}");
    } catch (error) {
      Log.error("Unexpected error while showing paywall: $error");
    }
```
