### ISSUE TITLE
Error: Type 'AdaptyIOSProductsFetchPolicy' not found.

### ISSUE THREAD

**Issue by davidequadrelli-b** [adaptyteam/AdaptyUI-Flutter#2]
On version 1.1.0  of the package, the class `AdaptyIOSProductsFetchPolicy` is not defined. The error is also declared on the 
[pub dev package page](https://pub.dev/packages/adapty_ui_flutter/score).

The stacktrace obtained is the following:
```
- 'AdaptyUI' is from 'package:adapty_ui_flutter/src/adaptyui.dart' ('../../.pub-cache/hosted/pub.dev/adapty_ui_flutter-1.1.0/lib/src/adaptyui.dart').
adaptyui.dart:1

Try correcting the name to the name of an existing getter, or defining a getter or field named 'AdaptyIOSProductsFetchPolicy'.
              fetchPolicy = AdaptyIOSProductsFetchPolicy.defaultPolicy;
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: 'AdaptyIOSProductsFetchPolicy' isn't a type.
adaptyui_observer.dart:99
  void paywallViewDidFailLoadingProducts(AdaptyUIView view, AdaptyIOSProductsFetchPolicy? fetchPolicy, AdaptyError error) {}
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

On Android the error above  occurs only when you try to present the paywallView.
On iOs the app doesn't compile with the following error:
```
Swift Compiler Error (Xcode): Cannot find type 'AdaptyProductsFetchPolicy' in scope
/Users/davide.quadrelli/.pub-cache/hosted/pub.dev/adapty_ui_flutter-1.1.0/ios/Classes/Adapty+Encoding.swift:41:10

Swift Compiler Error (Xcode): Cannot find type 'AdaptyProductsFetchPolicy' in scope
/Users/davide.quadrelli/.pub-cache/hosted/pub.dev/adapty_ui_flutter-1.1.0/ios/Classes/AdaptyUI+Delegate.swift:118:69
```

My flutter doctor output is the following
```
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5 22G74 darwin-arm64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

**Comment by x401om** [comment]
Hey, @davidequadrelli-b! `AdaptyIOSProductsFetchPolicy` was removed in AdaptySDK 2.6.x, and it looks like we have too weak dependency rules for AdaptyUI for now. I recommend you to downgrade AdaptySDK to 2.4.4 or remove AdaptyUI, since it does not support the new AdaptyUI 2.0 (we are planning to update it in the following weeks).

**Comment by davidequadrelli-b** [comment]
Hey @x401om , there are any news about the issue?

**Comment by x401om** [comment]
Hi @davidequadrelli-b! We are currently in the testing process for the AdaptyUI-Flutter update. I hope it will be available this week.

**Comment by x401om** [comment]
Hey, @davidequadrelli-b! You can check out the new version of [AdaptyUI-Flutter](https://github.com/adaptyteam/AdaptyUI-Flutter/releases/tag/2.0.0)!
