### ISSUE TITLE
Enabling Dialog Presentation Over Native Screens

### ISSUE THREAD

**Issue by ilknurimamhaliloglu** [adaptyteam/AdaptyUI-Flutter#6]
If user has performed some action or failed some action, I want to a show dialog on the view I open. How can I do that? I can listen the handling events but I can't show the dialog use with context, it stays under the view.

https://docs.adapty.io/docs/paywall-builder-events-flutter

**Comment by x401om** [comment]
Hi @ilknurimamhaliloglu, thank you for reaching out. At the moment, we don't support these options. If you plan to present anything above the standard native view, you'll need to implement it yourself, which I believe is only feasible with native code.

But, I think your request is quite a good enhancement, and we will consider adding this option in future releases.

**Comment by ilknurimamhaliloglu** [comment]
Thanks for your answer, I will be waiting for the enhancement.

**Comment by x401om** [comment]
Hey @ilknurimamhaliloglu! Good news – we've added the requested feature to our new version [2.1.0](https://github.com/adaptyteam/AdaptyUI-Flutter/releases/tag/2.1.0). Simply use the `.showDialog` method of the `AdaptyUIView`, and you're good to go! Please consider updating.

**Comment by mustafaacoskun** [comment]
I want to redirect to a bottom sheet or any other page within the openUrl section of the paywall, but I'm unable to do so because all such attempts stay behind the paywall. How can I resolve this issue?
